# -*- coding: utf-8 -*-
"""Hadoop installation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h8_WFUNXV_QyEc7gRZt6nC4PwJS_XVx4
"""

!sudo apt update

!sudo apt install default-jdk

!java -version

!wget https://downloads.apache.org/hadoop/common/hadoop-3.3.0/hadoop-3.3.0.tar.gz

!wget https://dist.apache.org/repos/dist/release/hadoop/common/hadoop-3.0.3/hadoop-3.0.3.tar.gz.mds

!tar -xzvf hadoop-3.3.0.tar.gz

!cp -r hadoop-3.3.0 /usr/local/hadoop

!/usr/local/hadoop/bin/hadoop

!mkdir ~/input
!cp /usr/local/hadoop/etc/hadoop/*.xml ~/input

!ls ~/input

!cp /usr/local/hadoop/etc/hadoop/*.xml ~/input

!/usr/local/hadoop/bin/hadoop jar /usr/local/hadoop/share/hadoop/mapreduce/hadoop-mapreduce-examples-3.3.0.jar grep ~/input ~/grep_example 'allowed[.]*'

!cat ~/grep_example/*

!pwd

!cd ~

!mkdir hadoopMR

!cd hadoopMR/

!ls

!python mapper.py